services:
  db:
    image: postgres:alpine3.23
    container_name: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data:rw
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf:z
    ports:
      - "5432"
    networks:
      - ft
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    restart: unless-stopped
