services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.2.2
    container_name: es01
    env_file:
      - .env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - elasticsearch_certs:/usr/share/elasticsearch/config/certs
    networks:
      - elastic
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -s -u elastic:${ELASTIC_PASSWORD} http://localhost:9200/_cluster/health | grep -vq ''"status":"red"''',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  filebeat:
    image: docker.elastic.co/beats/filebeat-wolfi:9.2.2
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:z
      - logs:/var/log/:ro
    depends_on:
      - logstash
    networks:
      - elastic
      - ft

  kibana:
    image: docker.elastic.co/kibana/kibana-wolfi:9.2.2
    container_name: kibana
    ports:
      - "5601:5601"
    env_file:
      - .env
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash-wolfi:9.2.2
    container_name: logstash
    env_file:
      - .env
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:z
      - elasticsearch_certs:/usr/share/logstash/config/certs:ro
    ports:
      - "5044:5044"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic

volumes:
  elasticsearch_data:
  elasticsearch_certs:
  logs:
    external: true

networks:
  elastic:
    name: elastic
  ft:
    external: true
