blank_issues_enabled: true
contact_links:
  - name: ğŸ“– Documentation ft_transcendence
    url: https://github.com/c-andriam/transcendence/blob/main/ft_transcendence.md
    about: Consultez le sujet du projet pour plus d'informations sur les modules et exigences
  - name: ğŸ“‹ GitHub Project Board
    url: https://github.com/c-andriam/transcendence/projects
    about: Voir le tableau Kanban du projet pour le suivi des tÃ¢ches
