services:
    prometheus:
        image: quay.io/prometheus/prometheus:v3.8.1
        container_name: prometheus
        ports:
            - "9090"
        volumes:
            - prometheus_data:/prometheus
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:z
            - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml:z
        networks:
            - monitor_net
        restart: unless-stopped

    alertmanager:
        image: quay.io/prometheus/alertmanager:v0.25.0
        container_name: alertmanager
        ports:
            - "9093:9093"
        volumes:
            - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:z
        networks:
            - monitor_net
        restart: unless-stopped

    grafana:
        image: grafana/grafana
        container_name: grafana
        environment:
            - GF_SECURITY_ADMIN_USER=${ADMIN}
            - GF_SECURITY_ADMIN_PASSWORD=${PASSW}
            - GF_USERS_ALLOW_SIGN_UP=false
        ports:
            - "3000:3000"
        volumes:
            - grafana_data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning:z
            - ./grafana/dashboards:/var/lib/grafana/dashboards:z
        networks:
            - monitor_net
        restart: unless-stopped

    node-exporter:
        image: quay.io/prometheus/node-exporter:v1.10.2
        container_name: node_exporter
        restart: unless-stopped
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        networks:
            - monitor_net
