filebeat.autodiscover:
  providers:
    - type: docker
      host: "unix:///var/run/podman.sock"
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/lib/containers/storage/overlay-containers/${data.container.id}/userdata/ctr.log
        prospector.scanner.symlinks: true
        processors:
          - add_docker_metadata:
              host: "unix:///var/run/podman.sock"

output.elasticsearch:
  enabled: false

output.logstash:
  hosts: ["logstash:5044"]
